{
    "type": "bundle",
    "id": "bundle--e2e5f166-40fb-4545-9bb3-c5ab78f97ffa",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--fd4c608f-ebfc-4c17-947d-f79e854b4bb1",
            "created": "2025-01-09T19:01:40.927Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "revoked": false,
            "external_references": [
                {
                    "source_name": "Cisco Akira Ransomware OCT 2024",
                    "description": "Nutland, J. and Szeliga, M. (2024, October 21). Akira ransomware continues to evolve. Retrieved December 10, 2024.",
                    "url": "https://blog.talosintelligence.com/akira-ransomware-continues-to-evolve/"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-16T23:00:02.530Z",
            "description": "[Akira _v2](https://attack.mitre.org/software/S1194) will fail to execute if the targeted `/vmfs/volumes/` path does not exist or is not defined.(Citation: Cisco Akira Ransomware OCT 2024)",
            "relationship_type": "uses",
            "source_ref": "malware--929d0d4d-b7c6-4ee8-81eb-43c849294e27",
            "target_ref": "attack-pattern--853c4192-4311-43e1-bfbb-b11b14911852",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}