{
    "type": "bundle",
    "id": "bundle--1f062328-b8a5-43b2-b8ce-cf6fcbaf8d39",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--b2852e21-c31a-482a-85fd-00d0990ee8ea",
            "created": "2021-02-09T14:35:39.656Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "external_references": [
                {
                    "source_name": "ESET Bad Rabbit",
                    "description": "M.L\u00e9veille, M-E.. (2017, October 24). Bad Rabbit: Not\u2011Petya is back with improved ransomware. Retrieved January 28, 2021.",
                    "url": "https://www.welivesecurity.com/2017/10/24/bad-rabbit-not-petya-back/"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-28T16:05:54.097Z",
            "description": "[Bad Rabbit](https://attack.mitre.org/software/S0606) has used various Windows API calls.(Citation: ESET Bad Rabbit)",
            "relationship_type": "uses",
            "source_ref": "malware--2eaa5319-5e1e-4dd7-bbc4-566fced3964a",
            "target_ref": "attack-pattern--391d824f-0ef1-47a0-b0ee-c59a75e27670",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}