{
    "type": "bundle",
    "id": "bundle--ec62f4f7-e380-4c95-9952-9e4341e85832",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--eab39c6d-8ebc-4961-9c16-e7bb00bacc43",
            "created": "2025-03-22T15:18:57.651Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "revoked": false,
            "external_references": [
                {
                    "source_name": "Cybereason LumaStealer Undated",
                    "description": "Cybereaon Security Services Team. (n.d.). Your Data Is Under New Lummanagement: The Rise of LummaStealer. Retrieved March 22, 2025.",
                    "url": "https://www.cybereason.com/blog/threat-analysis-rise-of-lummastealer"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-16T22:55:16.113Z",
            "description": "[Lumma Stealer](https://attack.mitre.org/software/S1213)  has been delivered through phishing emails with malicious attachments.(Citation: Cybereason LumaStealer Undated)",
            "relationship_type": "uses",
            "source_ref": "malware--674c514f-e485-47a8-9d49-1aaa70de155b",
            "target_ref": "attack-pattern--2e34237d-8574-43f6-aace-ae2915de8597",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}