{
    "type": "bundle",
    "id": "bundle--d0f78537-b2d5-4bba-99b7-4862f54b89fb",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--f9957b8a-0ece-4d97-8a56-8ca320e1828d",
            "created": "2025-03-22T15:20:05.121Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "revoked": false,
            "external_references": [
                {
                    "source_name": "Cybereason LumaStealer Undated",
                    "description": "Cybereaon Security Services Team. (n.d.). Your Data Is Under New Lummanagement: The Rise of LummaStealer. Retrieved March 22, 2025.",
                    "url": "https://www.cybereason.com/blog/threat-analysis-rise-of-lummastealer"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-16T22:59:02.418Z",
            "description": "[Lumma Stealer](https://attack.mitre.org/software/S1213) has been delivered through phishing emails containing malicious links.(Citation: Cybereason LumaStealer Undated)",
            "relationship_type": "uses",
            "source_ref": "malware--674c514f-e485-47a8-9d49-1aaa70de155b",
            "target_ref": "attack-pattern--2b742742-28c3-4e1b-bab7-8350d6300fa7",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}